### ISSUE TITLE
文字の決定

### ISSUE THREAD

**Issue by raiga0310** [MahjongCUI/App#1]
Unicodeからひぱってくる場合、CUIに読み込めるようにエンコードが必要
+ リーチの時の横向きをどうするか
自分たちで表現する場合、枠文字みたいなのを使用して中身を見やすく

**Comment by raiga0310** [comment]
必要な文字
+ 字牌
    + 方角牌(4種)
    + 三元牌(3種)
+ 数字牌(以下1~9の9種)
    + 筒子
    + 萬子
    + 索子

**Comment by Snowman-s** [comment]
Windowsのコマンドプロンプトは標準ではShiftJISで出力されており(要検証)、Unicodeを扱うには非常に面倒である可能性があります。

従って、自分たちで表現したいと思います。

**Comment by Snowman-s** [comment]
今考えてるのが以下のような感じですが、どうでしょうか。

┌　┐┌　┐┌　┐┌　┐┌　┐┌　┐
　一 　一 　一 
　萬 　筒 　索　 白　 發 　 中
└　┘└　┘└　┘└　┘└　┘└　┘

実際は、コンソールの出力に合わせてサイズを調整したり、等幅フォントを用いる必要があると思いますが―――

**Comment by Snowman-s** [comment]
"┌　┐\n　一　\n　索　\n└　┘"

**Comment by Snowman-s** [comment]
表示の時には、

改行ごとに分断して、
１行目を連結して
２行目を連結して...
